use_frameworks!

platform :ios, '9.0'

target 'ZZHNetwork_Example' do
  pod 'ZZHNetwork', :path => '../'

  target 'ZZHNetwork_Tests' do
    inherit! :search_paths

    
  end
end

#
#target 'ZZHNetwork' do
#  pod 'AFNetworking', '~> 3.0'
#end
